version: 2.1
jobs:
  build:
    docker:
      - image: node:18
    working_directory: ~/DoomerMeter/frontend
    steps:
      - checkout:
          path: ~/DoomerMeter
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: 
            - build
  deploy:
    docker:
      - image: circleci/golang:1.9.6
    working_directory: ~/DoomerMeter/frontend
    steps:
      - checkout:
          path: ~/DoomerMeter
      - attach_workspace:
          at: .
      - restore_cache:
          key: v1-pkg-cache
      - run: go get -v github.com/bep/s3deploy
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg
      - run:
          name: Deploy to S3 and Cloudfront
          command: |
            s3 deploy -source=build/ -region=$AWS_REGION -key=$AWS_ACCESS_KEY_ID
              -secret=$AWS_SECRET_ACCESS_KEY -distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID
              -bucket=$BUCKET_NAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
